language: python
python:
  - "2.7"
install:
  - curl https://raw.githubusercontent.com/praekelt/unicore-cms/develop/utils/install_libgit2.sh | sh
  - pip install -r requirements.txt --use-wheel
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install coveralls --use-wheel
script:
  - py.test --verbose --cov ./elasticgit elasticgit
after_success:
  - coveralls
