language: python
python:
  - "2.7"
services:
- elasticsearch
install:
  - pip install -r requirements.txt --use-wheel
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install coveralls --use-wheel
script:
  - py.test elasticgit
after_success:
  - coveralls
